name: Push to DockerHub

on:
    push:
        branches:
            - main
        paths-ignore:
            - README.md

jobs:
    Push-to-Dockerhub:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Docker Login
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
            - name: Build Docker Image
              run: docker build --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/product-aggregator:1.1
            - name: Push to Docker
              run: docker push ${{ secrets.DOCKER_USERNAME }}/product-aggregator:1.1