name: Push to DockerHub

on:
    push:
        branches:
            - main
        paths-ignore:
            - README.md
jobs:
    Push-to-Dockerhub:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build and Push to DockerHub
              uses: MaximilianoBz/dockerhub-buildpush@v1.1
              with:
                registry_url: docker.io
                repository_name: ${{ secrets.DOCKER_USERNAME }}/product-aggregator:1.1
                user_name: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
                image_version: 1.1